// bits-lib.mjs - shared helpers for the bits-* scripts (not a runnable check by itself).
// loadInstrumented(tag, patches): reads the LIVE web/solver-core.js, rewrites its './rules.js' import to '../../web/rules.js',
//   applies string patches (hooks that call globalThis.__bits?.xxx), appends an `export { popcount, metrics, explain, daysUsed, dur }`
//   line, writes the result as solver-audit/repro/bits-copy-<tag>.gen.mjs and imports it. It is a COPY: the original is never touched.
//   Every patch only INSERTS a hook call in front of/after an existing statement, so the copy computes exactly what the original does.
//   If an anchor no longer exists in the source, it throws (so a refactor of solver-core.js cannot silently pass).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const CORE = path.join(here, '../../web/solver-core.js');

export const mulberry32 = (a) => () => { a |= 0; a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
export const hhmm = (m) => String(Math.floor(m / 60)).padStart(2, '0') + ':' + String(m % 60).padStart(2, '0');

export async function loadInstrumented(tag, patches = []) {
  const src = fs.readFileSync(CORE, 'utf8').replace(/\r\n/g, '\n');
  let out = src.replace("from './rules.js'", "from '../../web/rules.js'");
  for (const [anchor, repl] of patches) {
    if (!out.includes(anchor)) throw new Error('instrumentation anchor not found in web/solver-core.js: ' + anchor);
    out = out.replace(anchor, repl);
  }
  out += '\nexport { popcount, metrics, explain, daysUsed, dur };\n';
  const file = path.join(here, `bits-copy-${tag}.gen.mjs`);
  fs.writeFileSync(file, '// GENERATED by bits-lib.mjs from web/solver-core.js (instrumented copy, safe to delete)\n' + out);
  const a = new Set(src.split('\n'));
  const changedLines = out.split('\n').filter((l) => !a.has(l)).length;   // lines of the copy that do not exist in the original
  return { mod: await import(pathToFileURL(file).href), changedLines, file };
}

// Hook patches shared by the scripts. Each keeps the original statement and adds one call.
export const HOOKS = {
  // called at EVERY dfs node (also the leaf level) with the value bound() returns there
  node: ['    if (i === items.length) return leaf(mask);',
    '    globalThis.__bits?.node?.(i, bound(i, mask, val), mask, val, items.length); if (i === items.length) return leaf(mask);'],
  // called at every leaf with the metrics and the context (prefMask etc.)
  metrics: ['    const { m, info } = metrics(sel, mask, ctx);',
    '    const { m, info } = metrics(sel, mask, ctx); globalThis.__bits?.metrics?.(m, info, sel, mask, ctx);'],
  score: ['    const score = Object.entries(weights).reduce((a, [k, w]) => a + w * (m[k] ?? 0), 0);',
    '    const score = Object.entries(weights).reduce((a, [k, w]) => a + w * (m[k] ?? 0), 0); globalThis.__bits?.score?.(score, m);'],
};
